---
- name: Copy SSH public key to all hosts
  hosts: all
  become: true
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: "0700"

    - name: Copy SSH public key to authorized_keys
      copy:
        src: ~/.ssh/ansible.pub
        dest: ~/.ssh/authorized_keys
        mode: "0644"
        append: yes
